apiVersion: snapshot.kubevirt.io/v1alpha1
kind: VirtualMachineRestore
metadata:
  name: vm2-from-vm1-snap
spec:
  target:
    apiGroup: kubevirt.io
    kind: VirtualMachine
    name: vm2
  virtualMachineSnapshotName: vm1-snap
